server:
  port: 8080
spring:
  application:
    name: "Library Service"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/libraryDB
    driverClassName: org.h2.Driver
    username: libraryDB
    password: libraryDB
    name: libraryDB
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create