server:
  port: 3043
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: "Library Service"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/libraryDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: libraryDB
    password: libraryDB
    name: libraryDB
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update