export enum Action {

    CONSULT = "CONSULT",

    CREATE_CONSULT_USER = "CREATE_CONSULT_USER",
    MANAGE_BORROW = "MANAGE_BORROW",

    MANAGE_BOOK_PUBLISHER_AUTHOR = "MANAGE_BOOK_PUBLISHER_AUTHOR",

    MANAGE_USER = "MANAGE_USER"
}